### PR TITLE
Compatibility fix for more recent versions of ocaml + reflect usage of dune instead of jbuilder.

### PR DESCRIPTION
**Pull request by AbdallahS**

### CODE REVIEW

**Comment by maelvls** [comment]
Hi!

Thank you so much for the patch!  It seems great, I hadn't the chance to update this kind of things.

Do you mind adding a new entry at the top of the [changelog file](https://github.com/touist/touist/blob/master/CHANGELOG)? 

That would start with:

```
v3.6.0
  - Compiling touist (the command line tool) now requires OCaml >= 4.08.0.
```

**Comment by maelvls** [comment]
Wait, is that Abdallah Saffidine? I'm so glad to see you here!! 💝

**Comment by AbdallahS** [comment]
Just updated the changelog (and the .opam file to 4.08 instead of 4.07 accordingly). Let me know if you need anything else on this one!

**Comment by maelvls** [comment]
Excellent! Thank you so much for submitting your patch! 👍

CI is failing, I'll fix it as part of #317. Let's merge your PR now!

**Pull request merged**
